PIPELINE:
  ENV:
    DEV:    
      PIPELINE_NAME: DADOS_DEV
      INPUT_PATH: /opt/airflow/dev/raw
      OUTPUT_PATH: /opt/airflow/dev/trusted
      INPUT_FILE_NAME: gov.csv
      OUTPUT_FILE_NAME: gov_dev_{today}.csv
    PRD:    
      PIPELINE_NAME: DADOS_PRD
      INPUT_PATH: /opt/airflow/prd/raw
      OUTPUT_PATH: /opt/airflow/prd/trusted
      INPUT_FILE_NAME: gov.csv
      OUTPUT_FILE_NAME: gov_prd_{today}.csv
